in_file = open('C:/Users/nickh/Documents/mydata2.txt', 'r+')
in_file.seek(2)
print (in_file.tell())
print (in_file.read(1))
print (in_file.tell())
print (in_file.read(1))
print (in_file.tell())
print (in_file.read(1))
print (in_file.tell())
print (in_file.read(1))
print (in_file.tell())
print (in_file.read(1))
print ()
in_file.seek(9)
print (in_file.tell())
print (in_file.read(1))
print (in_file.tell())
print (in_file.read(1))
print (in_file.tell())
print (in_file.read(1))
print (in_file.tell())
print (in_file.read(1))
print (in_file.tell())
print (in_file.read(1))
print ()
in_file.seek(16)
print (in_file.tell())
print (in_file.read(1))
print (in_file.tell())
print (in_file.read(1))
print (in_file.tell())
print (in_file.read(1))
print (in_file.tell())
print (in_file.read(1))
print (in_file.tell())
print (in_file.read(1))
in_file.close()
